version: '3.5'
services:
    app: 
        build: app
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./app:/app
            - ./app/node_modules:/app/node_modules
        container_name: book-app
        build:
            context: ./app
        command: npm start
        ports:
            - "3000:3000"